# Generated by Django 4.1 on 2023-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=5.0, editable=False),
        ),
    ]
