# Generated by Django 4.1 on 2023-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_remove_order_products_order_total_price_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
