# Generated by Django 4.1 on 2023-03-07 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_shippinginfo_ship_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
