# Generated by Django 4.1 on 2023-03-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_remove_comment_id_alter_comment_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='temp_id',
            new_name='id',
        ),
    ]
