# Generated by Django 4.1 on 2023-03-31 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0016_favouriteitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("expiration", models.DateField()),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(), size=None
                    ),
                ),
                ("href", models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="favouriteitem",
            options={
                "verbose_name": "Favourite Item",
                "verbose_name_plural": "Favourite Items",
            },
        ),
    ]
